service:
    MAPPER:
        mapping-config: {}
        mapping-enabled: false
orchestration:
    MAPPER:
        mapping-config: {}
        mapping-enabled: true
    Sl-Or:
        virtualizer_type: SINGLE
adaptation:
    CLEAR-DOMAINS-AFTER-SHUTDOWN: false
    MANAGERS:
    - INTERNAL
    INTERNAL:
        module: escape.adapt.managers
        class: BasicDomainManager
        domain_name: INTERNAL
        adapters:
            TOPOLOGY:
                module: escape.adapt.adapters
                class: NFFGBasedStaticFileAdapter
                path: examples/escape-mn-topo.nffg
                log_dir: log/
                check_backward_links: true
